### ISSUE TITLE
[Frontend] CSS files

### ISSUE THREAD

**Issue by deploy-soon** [swsnu/swpp2019-team6#39]
component 개발하면서 기존 의도와 개발이 달라져서 이슈 올립니다.
기존 App.css와 index.css가 Material-ui를 쓰게 되면서 맞지 않는 부분이 있는 것 같아요.
index.css는 계속 쓰일 부분이 있을 것 같긴 한데 App.css 지금 쓰는 부분 있는지 궁금합니다.

- App.css [`942a18`](https://github.com/swsnu/swpp2019-team6/blob/942a189db9bb69e9dca71113fca53debc9eae617/frontend/src/App.css)

- index.css [`942a18`](https://github.com/swsnu/swpp2019-team6/blob/942a189db9bb69e9dca71113fca53debc9eae617/frontend/src/index.css)

**Comment by RXWE** [comment]
App.css나 index.css를 써서 작업을 한 적은 없어요. App.css를 바꾸면 그 밑에 있는 컴포넌트들도 영향을 받을 것 같긴 한데(e.g. App.css에 text-align이 center로 되어있어서 text 적으면 기본으로 가운데 정렬 되는 것 같아요) 고치셔도 문제 없어요!

**Comment by deploy-soon** [comment]
`App.css`에 logo 관련 tag도 있던데 이것도 이제 사용 안 하는건가요? 저는 텍스트 가운데 정렬이 불편해서요.. `App.css` 삭제해도 될까요?

**Comment by RXWE** [comment]
네 삭제해도 됩니다!
