### ISSUE TITLE
[Bug Reports] Please leave bug reports here

### ISSUE THREAD

**Issue by RXWE** [swsnu/swpp2019-team6#77]

**Comment by haesookim** [comment]
(버그는 아니지만...) Recent와 Popular 간의 구분이 조금 더 명확했으면 좋겠습니다! 지금은 거의 안 보여서요ㅠㅠ

**Comment by vionicbest** [comment]
![image](https://user-images.githubusercontent.com/38846024/70227457-f408ba00-1795-11ea-9efc-6fd4ed22cdb7.png)
태그 검색이 안되염 ㅎㅎ

**Comment by haesookim** [comment]
로그인 된 상태에서 링크를 재입력했더니 로그아웃되었습니다ㅠㅠ

**Comment by dreammerkr** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 와 같은 닉네임을 입력해도 available 하다고 나옵니다. available 하지않은 닉네임은 어떤 기준인가요?

**Comment by khsoo01** [comment]
로그인하지 않은 상태에서 /main 등 다른 곳에 들어가면 로그인 창으로 redirect를 해주지 않은 것 같습니다.

**Comment by ttoru96** [comment]
로그인 한 후 리다이렉션 된 페이지에서 아무것도 보이지 않습니다

환경: macOS Sierra
브라우저: chrome

**Comment by HaeTheong** [comment]
저도 main 페이지에서 TypeError: Cannot read property 'photo' of null
    at TravelOverviewBlock.js:60 가 뜨면서 아무 것도 안보이네요

**Comment by peterhyun** [comment]
저도 로그인 후 암것도 안보이네요...

**Comment by RXWE** [comment]
데이터가 많이 있는 상황에 대한 테스트를 해보지 않아서 지금 문제가 생긴 것 같습니다... 죄송합니다:cry:

**Comment by RXWE** [comment]
버그 리포트 올려주신 모든 분들 정말 감사드립니다:bow: 더 준비가 된 서비스를 보여드릴 수 있었으면 좋았을텐데, 빠른 시일 내 보완할 수 있도록 하겠습니다.
