### ISSUE TITLE
닉네임 체크

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team6#78]
![image](https://user-images.githubusercontent.com/33143827/70227414-e5220780-1795-11ea-8b27-01a002c2e6f5.png)
check nickname을 했는데 아무런 반응이 없습니다.

**Comment by iamsungyeonjoo** [comment]
sign in도 마찬가지로 눌러도 아무런 변화가 없습니다.

**Comment by vionicbest** [comment]
한글의 경우 nickname 체크가 안되는 것 같아요

**Comment by iamsungyeonjoo** [comment]
+그리고 나서 check email을 버튼을 따로 두기 보다 valid password처럼 입력하자 마자 바로바로
warning message를 띄워주면 좋을 것 같습니다.

**Comment by RXWE** [comment]
practice session 시간에 막 deploy에 성공해서 연결이 안정적이지 못했습니다. check nickname과 sign in 반응이 없었던 건  그 때문이었던 것 같습니다. 좋은 의견 주셔서 감사합니다!:smile:
