### ISSUE TITLE
로그인 후 메인 페이지가 표시되지 않습니다.

### ISSUE THREAD

**Issue by eodmsabc** [swsnu/swpp2019-team6#79]
로그인 성공하고 /main으로 redirect는 되지만
화면에 내용이 나타나지 않습니다

내용이 뜨는 듯 하다가
Console에
Cannot read property 'photo' of null 에러가 나타나며 내용이 사라집니다

**Comment by jinsun1117** [comment]
(참고)
![image](https://user-images.githubusercontent.com/38969914/70227617-3e8a3680-1796-11ea-8475-9cab8cef816e.png)

**Comment by haesookim** [comment]
처음에는 나오다가 갑자기 안 뜨고 있어요!

**Comment by davin111** [comment]
#80 도 마찬가지 issue입니다.

**Comment by RXWE** [comment]
코드에 버그가 있었습니다. 소중한 시간에 빈 화면 보여드리게 되어 정말 죄송합니다.:cry:

**Comment by deploy-soon** [comment]
관련 버그 해결되었습니다!

- [`3dc231`](https://github.com/swsnu/swpp2019-team6/commit/3dc2317aaa5db6b3b3aabd9a8d5124a7bab7d96a)
