### ISSUE TITLE
Views(temporary)

### ISSUE THREAD

**Issue by RXWE** [swsnu/swpp2019-team6#8]
모바일 웹 기준으로 디자인하였습니다. 대부분의 컴포넌트가 한 줄 전체를 차지하기에, PC 환경에서 접속했을 때 컴포넌트 좌우 폭을 넓혀주는 식으로 보이게 하면 큰 문제 없을 듯합니다.

# /login
<img src="https://user-images.githubusercontent.com/37146511/67083964-0d9a7600-f1d7-11e9-9aef-bc182730bf8d.png" width="50%" >

# /sign_up
<img src="https://user-images.githubusercontent.com/37146511/67083970-0ffcd000-f1d7-11e9-805a-e920ad120d89.png" width="50%" >

# /search
<img src="https://user-images.githubusercontent.com/37146511/67083984-14c18400-f1d7-11e9-81b6-62781a3d24bd.png" width="50%" >

# /travel/:id
<img src="https://user-images.githubusercontent.com/37146511/67083992-17bc7480-f1d7-11e9-9247-4a81839ddcbe.png" width="50%" >

# /travel/create
<img src="https://user-images.githubusercontent.com/37146511/67084002-1ab76500-f1d7-11e9-83ab-093b5e77dcb0.png" width="50%" >

### Issue
travel의 전체적인 정보를 담는 블록이 커졌습니다. travel item을 끌어올 수 있는 팔레트(?)를 화면 아래에 항상 위치하는 floating block으로 구현하려면 create/edit 페이지에서 info 탭과 plan 탭을 구분하는 편이 낫지 않을까 싶습니다.

# /user/:id
<img src="https://user-images.githubusercontent.com/37146511/67084019-230fa000-f1d7-11e9-8baa-88396027c359.png" width="50%" >

**Comment by jangdonghae** [comment]
잘 만드셨습니다! 디자인도 좋은 것 같아요. 궁금한 점이 있는데 우측 상단 버튼을 누르면 정확히 어디로 가는 건가요??

**Comment by deploy-soon** [comment]
component가 직관적이고 보기 쉽습니다 😆 
그중 몇가지 궁금한게 있는데

1. 로그린 후 기본적으로 보이는 화면과 검색시 보이는 화면이 보이는 틀은 같지만 내용이 달라서 이 부분을 따로 구현하던가 url을 분리하는 것이 좋을 것 같습니다.
2. `/travel/:id` travel schedule detail page에서 댓글 위에 추천 여행 목록 몇가지 서빙하기로 했던 것 같은데 빠진 것 같아서 말씀드립니다.
3. Create Schedule에서 기존 기획처럼 icon 변경 기능도 추가하는지요
4. Create Schedule에서 Summary와 Description의 차이를 저희는 잘 알 것 같은데 화면을 보니 쓰는 사람 입장에서는 큰 차이를 못 느낄 것도 같네요..
5. Create Schedule에서 floating 관련 말씀은 이해가는데 Create/edit에서 탭을 구분한다는 말씀은 혹시 어떤 느낌인지 모호해서 그런데요 subheader를 추가해서 탭을 눌러 정보를 바꿔 본다는 뜻일까요?

**Comment by RXWE** [comment]
@jangdonghae 
우측 상단엔 본인 프로필이랑 삼각형 누르면 마이페이지, 로그아웃, ... 등의 메뉴가 나오게 할 것 같아요.
좌측 상단은 다른 사이트들 참고해 보니까 뒤로가기나 메인페이지로 돌아가기를 넣던데, 뒤로가기 버튼은 PC나 모바일 웹 브라우저에 탑재되어 있으니까 일단 메인페이지로 돌아가는 걸로 넣고 나중에 바꾸면 어떨까 싶어요.

@deploy-soon 
1. 그렇네요. Recent/Popular 보여주는 페이지를 /main 페이지로 놓고 search 결과를 /search 페이지로 놓는 식으로 하면 괜찮을까요?
2. 깜빡했네요 반영하겠습니다!
3. 하단 item block의 종류와 그 item block이 포함하는 활동의 범위도 더 생각해볼 필요가 있을 것 같은데, 일단 item block의 종류와 관련된 icon으로 바꿀 수 있는 걸 생각했어요.(ex 첫 번째 교통 item block은 택시/버스/비행기/배 icon으로 변경할 수 있게)
4. summary보다 여행의 느낌을 담아내라는 단어를 쓰면 좋을 것 같아요. 여행의 테마? 컨셉?을 알려달라는 식으로 바꾸면 어떨까요?
5. 네 맞아요. create schedule에서 subheader를 추가하고 그 중 info(?) 탭에서는 title/summary/tags/period/description을 입력할 수 있도록 하고, plan(?) 탭에서는 item blocks를 담고 있는 floating 팔레트를 화면 아래에 띄우고 날짜 추가 / item 추가 등 계획 수정과 관련된 부분만을 작업하도록요. 구성상 둘을 분리해줘야 맞을 것 같은데, 이렇게 할 경우 구현이 조금 복잡해지진 않을까 걱정이네요.

**Comment by dreamsh19** [comment]
고생하셨습니다
@RXWE 



> @jangdonghae
> 우측 상단엔 본인 프로필이랑 삼각형 누르면 마이페이지, 로그아웃, ... 등의 메뉴가 나오게 할 것 같아요.
> 좌측 상단은 다른 사이트들 참고해 보니까 뒤로가기나 메인페이지로 돌아가기를 넣던데, 뒤로가기 버튼은 PC나 모바일 웹 브라우저에 탑재되어 있으니까 일단 메인페이지로 돌아가는 걸로 넣고 나중에 바꾸면 어떨까 싶어요.
> 
우측 상단 화살표 아래로는 마이 페이지, 로그아웃 두 가지만 일단 구현하고 후에 필요한 요소를 추가하는게 어떨까요?

> @deploy-soon
> 
> 1. 그렇네요. Recent/Popular 보여주는 페이지를 /main 페이지로 놓고 search 결과를 /search 페이지로 놓는 식으로 하면 괜찮을까요?

/main 페이지와 /search 페이지로 하는 것이 좋을 것 같아요!


> 3. 하단 item block의 종류와 그 item block이 포함하는 활동의 범위도 더 생각해볼 필요가 있을 것 같은데, 일단 item block의 종류와 관련된 icon으로 바꿀 수 있는 걸 생각했어요.(ex 첫 번째 교통 item block은 택시/버스/비행기/배 icon으로 변경할 수 있게)

하단 floating block에 둘 아이콘은 위의 구현처럼 6개(Transportation, Food, Sight, Accomodation, Activity, Custom(etc))로 고정하는 것이 복잡하지 않고 좋을 것 같습니다. 말씀하신 교통 item block을 택시/버스/비행기 icon 등의 세부 아이콘으로 바꾸는 것과 같은 기능을 구현한다면, 그 아이콘을 끌어서 실제로 travel unit block을 생성할 때 바꾸도록 하는 게 좋을 것 같습니다.

> 4. summary보다 여행의 느낌을 담아내라는 단어를 쓰면 좋을 것 같아요. 여행의 테마? 컨셉?을 알려달라는 식으로 바꾸면 어떨까요?

네이밍이 가장 어렵네요. 지금 생각에는 Concept가 좋아보이는데, '한줄 요약'에 해당하는 적절한 영어 단어가 떠오르질 않네요

> 5. 네 맞아요. create schedule에서 subheader를 추가하고 그 중 info(?) 탭에서는 title/summary/tags/period/description을 입력할 수 있도록 하고, plan(?) 탭에서는 item blocks를 담고 있는 floating 팔레트를 화면 아래에 띄우고 날짜 추가 / item 추가 등 계획 수정과 관련된 부분만을 작업하도록요. 구성상 둘을 분리해줘야 맞을 것 같은데, 이렇게 할 경우 구현이 조금 복잡해지진 않을까 걱정이네요.

저도 두 개의 탭으로 분리하는 게 좋다고 생각해요. 분리를 안하니까 페이지가 상하로 너무 긴 느낌이 있네요. 말씀하신대로 실제 plan에 해당하는 탭과 그 외의 정보들을 담는 탭으로요. 그리고 travel detail(/travel/:id) 페이지에서도 같은 방식으로 두 개의 탭으로 구성하는게 좋을 것 같은데 어떻게 생각하시나요? 두 개의 탭으로 분리한다면 Comment를 어느 탭에 넣을지에 대한 논의도 필요할 것 같습니다.

**Comment by dreamsh19** [comment]
추가적으로  현재 각 페이지가 해당 url로 명시되어있는데 
각 페이지의 이름을 travel_detail, create_travel과 같이 구체적으로 명시해서 url과 같이 적어놓으면
앞으로 개발할 때도 계속 reference하면서 이름으로 인한 혼선을 줄일 수 있을 것 같습니다 :)

**Comment by RXWE** [comment]
@dreamsh19 
 > 우측 상단 화살표 아래로는 마이 페이지, 로그아웃 두 가지만 일단 구현하고 후에 필요한 요소를 추가하는게 어떨까요?

네 일단 그렇게 할게요!

> /main 페이지와 /search 페이지로 하는 것이 좋을 것 같아요!
> ( 추가 : /main 대신 /timeline 은 어떨까요 ? )

페이스북에서처럼 유저별로 고유한 timeline을 주는 게 아니라 (아직까지는) 모든 유저에게 공통된 popular와 recent를 보여주기도 하고, 공지사항이나 이벤트를 안내해 줄 페이지가 필요하다는 점에서 timeline보다는 main이 좋지 않을까 싶어요. 일단 main으로 쓰고 나중에 더 논의해봐요!

> 하단 floating block에 둘 아이콘은 위의 구현처럼 6개(Transportation, Food, Sight, Accomodation, Activity, Custom(etc))로 고정하는 것이 복잡하지 않고 좋을 것 같습니다. 말씀하신 교통 item block을 택시/버스/비행기 icon 등의 세부 아이콘으로 바꾸는 것과 같은 기능을 구현한다면, 그 아이콘을 끌어서 실제로 travel unit block을 생성할 때 바꾸도록 하는 게 좋을 것 같습니다.

네 그렇게 하겠습니다.

> 네이밍이 가장 어렵네요. 지금 생각에는 Concept가 좋아보이는데, '한줄 요약'에 해당하는 적절한 영어 단어가 떠오르질 않네요

일단 제출하고 더 생각해봐야 할 것 같아요...

> 저도 두 개의 탭으로 분리하는 게 좋다고 생각해요. 분리를 안하니까 페이지가 상하로 너무 긴 느낌이 있네요. 말씀하신대로 실제 plan에 해당하는 탭과 그 외의 정보들을 담는 탭으로요. 그리고 travel detail(/travel/:id) 페이지에서도 같은 방식으로 두 개의 탭으로 구성하는게 좋을 것 같은데 어떻게 생각하시나요? 두 개의 탭으로 분리한다면 Comment를 어느 탭에 넣을지에 대한 논의도 필요할 것 같습니다.

에어비앤비나 트립닷컴에서 상품 설명을 볼 때 아래로 길더라도 한 페이지에 다 넣더라고요. 정보를 확인하는 데 스크롤만 사용하도록 UX를 고려한 것 같은데, 저는 detail 페이지가 위아래로 길더라도 이렇게 스크롤만 사용하는 것이니 괜찮을거라 생각했어요. create에선 floating items때문에 분리할 필요가 있었지만 detail에선 꼭 분리해야 할 필요가 없으니 지금처럼 해도 괜찮을 것 같다는 생각이에요! 다른 분들의 의견은 어떠신가요??

**Comment by RXWE** [comment]
![View](https://user-images.githubusercontent.com/37146511/67139532-4a747480-f28c-11e9-8f52-f5f335f49838.png)
