### ISSUE TITLE
Main Page에 아무것도 나오지 않는 상황

### ISSUE THREAD

**Issue by davin111** [swsnu/swpp2019-team6#80]
<img width="1202" alt="스크린샷 2019-12-05 19 33 09" src="https://user-images.githubusercontent.com/35535636/70227593-34683800-1796-11ea-9478-46075f855f1f.png">

무언가 조금 이곳저곳 돌아다니다보니, /main 에 아무것도 뜨지 않는 상태로 stuck되었습니다.
새로고침 해도 아주 짧은 순간, Popular, Regular 등이 보이고 마찬가지의 상황이 됩니다.

**Comment by RXWE** [comment]
#79에서 답변드린 것과 같이 코드에 버그가 있었습니다. 소중한 시간에 빈 화면 보여드리게 되어 정말 죄송합니다.:cry:

**Comment by deploy-soon** [comment]
관련 버그 해결되었습니다!

- [`3dc231`](https://github.com/swsnu/swpp2019-team6/commit/3dc2317aaa5db6b3b3aabd9a8d5124a7bab7d96a)
