### ISSUE TITLE
로그인 후 하얀 화면에 멈췄어요

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team6#81]
![image](https://user-images.githubusercontent.com/33143827/70227699-637ea980-1796-11ea-851c-f58b839c7938.png)

**Comment by RXWE** [comment]
#79에서 답변드린 것과 같이 코드에 버그가 있었습니다. 소중한 시간에 빈 화면 보여드리게 되어 정말 죄송합니다.:cry:

**Comment by deploy-soon** [comment]
관련 버그 해결되었습니다!

- [`3dc231`](https://github.com/swsnu/swpp2019-team6/commit/3dc2317aaa5db6b3b3aabd9a8d5124a7bab7d96a)
