### ISSUE TITLE
[Backend] User view - How to check password and change password?

### ISSUE THREAD

**Issue by RXWE** [swsnu/swpp2019-team6#88]
https://github.com/swsnu/swpp2019-team6/blob/07f0b9eb56b599a5bf24ccd0a38bd93c1f74f159/backend/triplannet/user/views.py#L90-L102
Issue #12 를 참고하여 /api/user/:id/에 PUT request를 보내면 user 정보를 업데이트하는 코드를 짜고 있습니다.
가능한 request data는
```
{
  "current_password": "mypassword",
  "new_password": "mypasssword2",
  "nickname": "mynickname",
  "status_message": "mymessage..."
}
```
이고 password(current & new), nickname, status_message 중 하나씩만 보낼 수도 있습니다.

password를 변경할 때
1. user의 저장된 password와 입력한 current password가 같은지 확인한다.
2. 다르면 400 response를 보낸다.
3. 올바른 current password가 입력되었을 경우 password를 new_password로 변경한다.
로 생각하고 위와 같은 코드를 작성했습니다.

그런데 password를 저장할 때 암호화? serialize? 하여 저장해서, 항상 current password를 잘못 입력했다고 뜹니다.

![image](https://user-images.githubusercontent.com/37146511/70299196-8f9e3700-1837-11ea-8a93-ad5e01423e51.png)
위 줄이 `user.password`를 출력한 결과이고, 아래가 `request.data.get('current_password')`를 출력한 결과입니다. 확인 절차를 생략하고 바로
```
user.password = request.data.get("new_password", user.password) 
```
가 실행되도록 해서 다시 로그인하려 하면 바꾼 비밀번호로 로그인이 안 되는 것으로 보아, user.password를 다룰 때 Login이나 Signup할 때처럼 암호화? serialize? 처리를 해줘야할 것 같습니다.
일단 password 변경 기능은 항상 current password가 잘못 입력되었다고 뜨는 채로 두긴 했는데, 시간 되실 때 이 부분 도와주시면 감사하겠습니다..!

**Comment by deploy-soon** [comment]
password를 그냥 저장하면 장고에서 해싱해서 저장하는 것으로 알고 있었는데 생각해보니 비교를 저렇게 하면 안 되겠네요.

**Comment by dreamsh19** [comment]
`from django.contrib.auth.hashers import check_password`
후에
`check_password(current_password,user.password)`
와 같이 하면 될 것 같습니다.

참고 
https://ssungkang.tistory.com/entry/DjangoUser-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0-checkpassword

**Comment by RXWE** [comment]
@dreamsh19 감사합니다. 시도해 보겠습니다!

**Comment by RXWE** [comment]
@dreamsh19 님이 알려주신 방법대로 하니까 잘 되네요. 감사합니다:smile:
